In [2]:
from __future__ import print_function
import torch
import numpy as np

In [3]:
# Autograd：自动求导

# autograd 包为张量上的所有操作提供了自动求导.它是一个运行时定义的框架,这意味着反向传播
# 是根据你的代码如何运行来定义,并且每次迭代可以不同.# autograd 包为张量上的所有操作提供了自动求导.它是一个运行时定义的框架,这意味着反向传
# 播是根据你的代码如何运行来定义,并且每次迭代可以不同.

In [4]:
# 张量(Tensor)
# torch.Tensor 是包的核心类。如果将其属性.requires_grad 设置为True，则会开始跟踪其上
# 的所有操作。完成计算后，您可以调用.backward() 并自动计算所有梯度。此张量的梯度将累
# 积到.grad 属性中。
# 要阻止张量跟踪历史记录，可以调用.detach() 将其从计算历史记录中分离出来，并防止将来
# 的计算被跟踪。
# 要防止跟踪历史记录（和使用内存），您还可以使用torch.no_grad()包装代码块：在评估模型
# 时，这可能特别有用，因为模型可能具有requires_grad = True 的可训练参数，但我们不需要
# 梯度。
# 还有一个类对于autograd实现非常重要 - Function。
# Tensor和Function互相连接并构建一个非循环图构建一个完整的计算过程。每个张量都有一
# 个.grad_fn 属性，该属性引用已创建Tensor的Function（除了用户创建的Tensors - 它们的gr
# ad_fn 为None ）。
# 如果要计算导数，可以在Tensor上调用.backward() 。如果Tensor是标量（即它包含一个元素
# 数据），则不需要为backward() 指定任何参数，但是如果它有更多元素，则需要指定一个梯度
# 参数，该参数是匹配形状的张量。

# 创建一个张量，并设置requires_grad = True以跟踪它的计算
x = torch.rand(2, 2, requires_grad=True)
# print(x)
y = x + 2
# print(y) # 因为y是一个操作创建的，所有他又grad_fn
# x是用户创建的，其grad_fn未None
z = y * y * 3
out = z.mean()
print(z, out)

# .requires_grad_(...) 就地更改现有的Tensor的requires_grad 标志。如果没有给出，输入
# 标志默认为False。
a = torch.rand(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True) # 修改require_grad标志
print(a.requires_grad)

tensor([[15.2029, 19.6201],
        [21.3262, 13.6940]], grad_fn=<MulBackward0>)tensor(17.4608, grad_fn=<MeanBackward0>)
False
True


In [5]:
# 梯度（Gradients)
# 现在我们来执行反向传播, out.backward() 相当于执行out.backward(torch.tensor(1.))
# out.backward()
# print(x.grad) # 输出out对x的梯度d(out)/dx;

# 雅可比向量积的例子
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)
# 现在在这种情况下，y不再是标量。torch.autograd 无法直接计算完整雅可比行列式，但如果
# 我们只想要雅可比向量积，只需将向量作为参数向后传递：
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

# 您还可以通过torch.no_grad()代码，在张量上使用.requires_grad = True来停止使用跟踪历史记录。
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

tensor([ 1114.2261, -1074.0837,   194.3085], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
True
True
False
